services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false     # 로컬 개발 편의용
      - ES_JAVA_OPTS=-Xms1g -Xmx1g       # 메모리 조절
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    command: >
      bash -c "
        elasticsearch-plugin install analysis-nori --batch;
        exec elasticsearch
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    ports:
      - "5601:5601"

volumes:
  esdata: